nelmio_api_doc:
    documentation:
        info:
            title: AuctionX API
            description: AuctionX brings auctions to the Immutable X ecosystem.
            version: 1.1.0
        servers:
            - url: 'https://%env(SERVER_NAME)%'
    areas: # to filter documented areas
        path_patterns:
            - ^/v1(?!/(docs|docs.json|messages)$) # Accepts routes under /v1 except /v1/docs, /v1/doc.json & /v1/messages (private api)
    models:
        names:
            # Auctions
            - { alias: Auction.item, type: App\Entity\Auction, groups: [ get-auction, get-auction-with-asset, get-auction-with-bids ] }
            - { alias: Auction.list, type: App\Entity\Auction, groups: [ get-auction ] }
            - { alias: Auction.post, type: App\Entity\Auction, groups: [ post-auction ] }
            # Assets
            - { alias: Asset.item, type: App\Entity\Asset, groups: [ get-asset, get-asset-with-auctions, get-asset-with-collection ] }
            - { alias: Asset.list, type: App\Entity\Asset, groups: [ get-asset ] }
            # Collections
            - { alias: Collection.item, type: App\Entity\Collection, groups: [ get-collection ] }
            - { alias: Collection.list, type: App\Entity\Collection, groups: [ get-collection ] }
            # Bids
            - { alias: Bid.item, type: App\Entity\Bid, groups: [ get-bid, get-bid-with-auction ] }
            - { alias: Bid.list, type: App\Entity\Bid, groups: [ get-bid ] }
            # Miscellaneous
            - { alias: HealthCheck.item, type: App\Model\HealthCheck, groups: [ get-health-check ] }
            - { alias: Wallet.item, type: App\Model\Wallet, groups: [ get-wallet ] }
