nelmio_api_doc:
    documentation:
        info:
            title: Auction X API
            description: Auction X brings auctions to the Immutable X ecosystem.
            version: 1.0.0
        servers:
            - url: 'https://%env(SERVER_NAME)%'
    areas: # to filter documented areas
        path_patterns:
            - ^/api/v1(?!/(documentation|doc.json)$) # Accepts routes under /api/v1 except /api/v1/documentation & /api/v1/doc.json
    models:
        names:
            - { alias: Auction.item, type: App\Entity\Auction, groups: [ get-auction ] }
            - { alias: Auction.list, type: App\Entity\Auction, groups: [ get-auction, get-auction-with-asset ] }
            - { alias: Auction.post, type: App\Entity\Auction, groups: [ post-auction ] }
            - { alias: Asset.item, type: App\Entity\Asset, groups: [ get-asset ] }
            - { alias: Asset.list, type: App\Entity\Asset, groups: [ get-asset, get-asset-with-auctions ] }
            - { alias: HealthCheck.item, type: App\Model\HealthCheck, groups: [ get-health-check ] }
            - { alias: Wallet.item, type: App\Model\Wallet, groups: [ get-wallet ] }
