nelmio_api_doc:
    documentation:
        info:
            title: Auction X API
            description: Auction X brings auctions to the Immutable X ecosystem.
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api/v1(?!/(documentation|doc.json)$) # Accepts routes under /api/v1 except /api/v1/documentation & /api/v1/doc.json
