nelmio_api_doc:
    documentation:
        info:
            title: AuctionX API
            description: AuctionX brings auctions to the Immutable X ecosystem.
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api/v1(?!/documentation$) # Accepts routes under /api/v1 except /api/documentation$
