nelmio_api_doc:
    documentation:
        info:
            title: Auction X API
            description: Auction X brings auctions to the Immutable X ecosystem.
            version: 1.0.0
        servers:
            - url: 'https://%env(SERVER_NAME)%'
    areas: # to filter documented areas
        path_patterns:
            - ^/api/v1(?!/(documentation|doc.json)$) # Accepts routes under /api/v1 except /api/v1/documentation & /api/v1/doc.json
    models:
        names:
            - { alias: GetAuction, type: App\Entity\Auction, groups: [ get-auction ] }
            - { alias: GetAuctionWithAsset, type: App\Entity\Asset, groups: [ get-auction-with-asset ] }
            - { alias: PostAuction, type: App\Entity\Auction, groups: [ post-auction ] }
            - { alias: GetAsset, type: App\Entity\Asset, groups: [ get-asset ] }
            - { alias: GetAssetWithAuctions, type: App\Entity\Asset, groups: [ get-asset-with-auctions ] }
            - { alias: GetHealthCheck, type: App\Model\HealthCheck, groups: [ get-health-check ] }
