when@prod:
    sentry:
        dsn: '%env(SENTRY_DSN)%'

    services:
        Sentry\Integration\IgnoreErrorsIntegration:
            arguments:
                $options:
                    ignore_exceptions:
                        - Symfony\Component\HttpKernel\Exception\NotFoundHttpException
                        - Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException
                        - Symfony\Component\Console\Exception\CommandNotFoundException
