# Expose your documentation as JSON swagger compliant
app_swagger:
    path: /v1/docs.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }

app_swagger_ui_v1:
    path: /v1/docs
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }
