app.controllers:
    resource: ../src/Controller/*.php
    type: annotation

api.controllers:
    resource: ../src/Controller/Api
    type: annotation
    prefix:
        name: 'v1'

kernel:
    resource: ../src/Kernel.php
    type: annotation